module.exports = {
  BORDER_RADIUS_DEFAULT: 1,
  COLOR: {
    ORANGE: "#ED5F23",
    BLUE: "#22408A",
    THEME_LIGHT: "#B5C2CF",
    THEME_DARK: "#6F8298",
    SUCCESS_GREEN: "#008000",
    DANGER_RED: "#F00",
    TEXT_COLOR_BLACK: "#000",
    TEXT_COLOR_ORANGE: '#ED5F23',
    WHITE_BACKGROUND: "#FFF"
  },
  ELEVATION_ANDROID: 2,
  FONT_SIZE: {
    SMALL: 12,
    STANDARD: 14,
    LARGE: 18,
    EXTRA_LARGE: 22,
  },
  PADDING_DEFAULT: 5,
  PADDING_DOUBLE: 10,
}
